-- Phoenix skillchain data.
-- A skill is listed here only when it can skillchain on Phoenix.

local sets = {}

sets.phoenix = {}
sets.phoenix[3] = {
--Hand-to-Hand
    [1] = {en='Combo',skillchain={'Impaction'}},
    [2] = {en='Shoulder Tackle',skillchain={'Reverberation','Impaction'}},
    [3] = {en='One Inch Punch',skillchain={'Compression'}},
    [4] = {en='Backhand Blow',skillchain={'Detonation'}},
    [5] = {en='Raging Fists',skillchain={'Impaction'}},
    [6] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
    [7] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [8] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [9] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [10] = {en='Final Heaven',skillchain={'Light','Fusion'}},
    [11] = {en='Ascetic\'s Fury',skillchain={'Fusion','Transfixion'}},
    [12] = {en='Stringing Pummel',skillchain={'Gravitation','Liquefaction'}},
    [13] = {en='Tornado Kick',skillchain={'Induration','Impaction','Detonation'}},
    [14] = {en='Victory Smite',skillchain={'Light','Fragmentation'}},
    [15] = {en='Shijin Spiral',skillchain={'Fusion','Reverberation'},aeonic='Light',weapon='Godhand'},
    [228] = {en='Final Paradise',skillchain={'Light'}},
--Dagger
    [16] = {en='Wasp Sting',skillchain={'Scission'}},
    [17] = {en='Viper Bite',skillchain={'Scission'}},
    [18] = {en='Shadowstitch',skillchain={'Reverberation'}},
    [19] = {en='Gust Slash',skillchain={'Detonation'}},
    [20] = {en='Cyclone',skillchain={'Detonation','Impaction'}},
    [23] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
    [24] = {en='Shark Bite',skillchain={'Fragmentation'}},
    [25] = {en='Evisceration',skillchain={'Gravitation','Transfixion'}},
    [26] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
    [27] = {en='Mandalic Stab',skillchain={'Fusion','Compression'}},
    [28] = {en='Mordant Rime',skillchain={'Fragmentation','Distortion'}},
    [29] = {en='Pyrrhic Kleos',skillchain={'Distortion','Scission'}},
    [30] = {en='Aeolian Edge',skillchain={'Scission','Detonation','Impaction'}},
    [31] = {en='Rudra\'s Storm',skillchain={'Darkness','Distortion'}},
    [224] = {en='Exenterator',skillchain={'Fragmentation','Scission'},aeonic='Light',weapon='Aeneas'},
--Sword
    [32] = {en='Fast Blade',skillchain={'Scission'}},
    [33] = {en='Burning Blade',skillchain={'Liquefaction'}},
    [34] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [35] = {en='Flat Blade',skillchain={'Impaction'}},
    [36] = {en='Shining Blade',skillchain={'Scission'}},
    [37] = {en='Seraph Blade',skillchain={'Scission'}},
    [38] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [40] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [41] = {en='Swift Blade',skillchain={'Gravitation'}},
    [42] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [43] = {en='Knights of Round',skillchain={'Light','Fusion'}},
    [44] = {en='Death Blossom',skillchain={'Fragmentation','Distortion'}},
    [45] = {en='Atonement',skillchain={'Fusion','Reverberation'}},
    [46] = {en='Expiacion',skillchain={'Distortion','Scission'}},
    [225] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [226] = {en='Requiescat',skillchain={'Gravitation','Scission'},aeonic='Darkness',weapon='Sequence'},
    [227] = {en='Knights of Rotund',skillchain={'Light'}},
    [238] = {en='Uriel Blade',skillchain={'Light','Fragmentation'}},
    [239] = {en='Glory Slash',skillchain={'Light','Fusion'}},
--Great Sword
    [48] = {en='Hard Slash',skillchain={'Scission'}},
    [49] = {en='Power Slash',skillchain={'Transfixion'}},
    [50] = {en='Frostbite',skillchain={'Induration'}},
    [51] = {en='Freezebite',skillchain={'Induration','Detonation'}},
    [52] = {en='Shockwave',skillchain={'Reverberation'}},
    [53] = {en='Crescent Moon',skillchain={'Scission'}},
    [54] = {en='Sickle Moon',skillchain={'Scission','Impaction'}},
    [55] = {en='Spinning Slash',skillchain={'Fragmentation'}},
    [56] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [57] = {en='Scourge',skillchain={'Light','Fusion'}},
    [58] = {en='Herculean Slash',skillchain={'Induration','Impaction','Detonation'}},
    [59] = {en='Torcleaver',skillchain={'Light','Distortion'}},
    [60] = {en='Resolution',skillchain={'Fragmentation','Scission'},aeonic='Light',weapon='Lionheart'},
    [61] = {en='Dimidiation',skillchain={'Light','Fragmentation'}},
--Axe
    [64] = {en='Raging Axe',skillchain={'Detonation','Impaction'}},
    [65] = {en='Smash Axe',skillchain={'Induration','Reverberation'}},
    [66] = {en='Gale Axe',skillchain={'Detonation'}},
    [67] = {en='Avalanche Axe',skillchain={'Scission','Impaction'}},
    [68] = {en='Spinning Axe',skillchain={'Liquefaction','Scission','Impaction'}},
    [69] = {en='Rampage',skillchain={'Scission'}},
    [70] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [71] = {en='Mistral Axe',skillchain={'Fusion'}},
    [72] = {en='Decimation',skillchain={'Fusion','Reverberation'}},
    [73] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
    [74] = {en='Primal Rend',skillchain={'Gravitation','Reverberation'}},
    [75] = {en='Bora Axe',skillchain={'Scission','Detonation'}},
    [76] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
    [77] = {en='Ruinator',skillchain={'Distortion','Detonation'},aeonic='Darkness',weapon='Tri-Edge'},
--Great Axe
    [80] = {en='Shield Break',skillchain={'Impaction'}},
    [81] = {en='Iron Tempest',skillchain={'Scission'}},
    [82] = {en='Sturmwind',skillchain={'Reverberation','Scission'}},
    [83] = {en='Armor Break',skillchain={'Impaction'}},
    [84] = {en='Keen Edge',skillchain={'Compression'}},
    [85] = {en='Weapon Break',skillchain={'Impaction'}},
    [86] = {en='Raging Rush',skillchain={'Induration','Reverberation'}},
    [87] = {en='Full Break',skillchain={'Distortion'}},
    [88] = {en='Steel Cyclone',skillchain={'Distortion','Detonation'}},
    [89] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
    [90] = {en='King\'s Justice',skillchain={'Fragmentation','Scission'}},
    [91] = {en='Fell Cleave',skillchain={'Scission','Detonation','Impaction'}},
    [92] = {en='Ukko\'s Fury',skillchain={'Light','Fragmentation'}},
    [93] = {en='Upheaval',skillchain={'Fusion','Compression'},aeonic='Light',weapon='Chango'},
--Scythe
    [96] = {en='Slice',skillchain={'Scission'}},
    [97] = {en='Dark Harvest',skillchain={'Reverberation'}},
    [98] = {en='Shadow of Death',skillchain={'Induration','Reverberation'}},
    [99] = {en='Nightmare Scythe',skillchain={'Compression','Scission'}},
    [100] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [101] = {en='Vorpal Scythe',skillchain={'Transfixion','Scission'}},
    [102] = {en='Guillotine',skillchain={'Induration'}},
    [103] = {en='Cross Reaper',skillchain={'Distortion'}},
    [104] = {en='Spiral Hell',skillchain={'Distortion','Scission'}},
    [105] = {en='Catastrophe',skillchain={'Darkness','Gravitation'}},
    [106] = {en='Insurgency',skillchain={'Fusion','Compression'}},
    [107] = {en='Infernal Scythe',skillchain={'Compression','Reverberation'}},
    [108] = {en='Quietus',skillchain={'Darkness','Distortion'}},
    [109] = {en='Entropy',skillchain={'Gravitation','Reverberation'},aeonic='Darkness',weapon='Anguta'},
--Polearm
    [112] = {en='Double Thrust',skillchain={'Transfixion'}},
    [113] = {en='Thunder Thrust',skillchain={'Transfixion','Impaction'}},
    [114] = {en='Raiden Thrust',skillchain={'Transfixion','Impaction'}},
    [115] = {en='Leg Sweep',skillchain={'Impaction'}},
    [116] = {en='Penta Thrust',skillchain={'Compression'}},
    [117] = {en='Vorpal Thrust',skillchain={'Reverberation','Transfixion'}},
    [118] = {en='Skewer',skillchain={'Transfixion','Impaction'}},
    [119] = {en='Wheeling Thrust',skillchain={'Fusion'}},
    [120] = {en='Impulse Drive',skillchain={'Gravitation','Induration'}},
    [121] = {en='Geirskogul',skillchain={'Light','Distortion'}},
    [122] = {en='Drakesbane',skillchain={'Fusion','Transfixion'}},
    [123] = {en='Sonic Thrust',skillchain={'Transfixion','Scission'}},
    [124] = {en='Camlann\'s Torment',skillchain={'Light','Fragmentation'}},
    [125] = {en='Stardiver',skillchain={'Gravitation','Transfixion'},aeonic='Darkness',weapon='Trishula'},
--Katana
    [128] = {en='Blade: Rin',skillchain={'Transfixion'}},
    [129] = {en='Blade: Retsu',skillchain={'Scission'}},
    [130] = {en='Blade: Teki',skillchain={'Reverberation'}},
    [131] = {en='Blade: To',skillchain={'Induration','Detonation'}},
    [132] = {en='Blade: Chi',skillchain={'Transfixion','Impaction'}},
    [133] = {en='Blade: Ei',skillchain={'Compression'}},
    [134] = {en='Blade: Jin',skillchain={'Detonation','Impaction'}},
    [135] = {en='Blade: Ten',skillchain={'Gravitation'}},
    [136] = {en='Blade: Ku',skillchain={'Gravitation','Transfixion'}},
    [137] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    [138] = {en='Blade: Kamu',skillchain={'Fragmentation','Compression'}},
    [139] = {en='Blade: Yu',skillchain={'Reverberation','Scission'}},
    [140] = {en='Blade: Hi',skillchain={'Darkness','Gravitation'}},
    [141] = {en='Blade: Shun',skillchain={'Fusion','Impaction'},aeonic='Light',weapon='Heishi Shorinken'},
--Great Katana
    [144] = {en='Tachi: Enpi',skillchain={'Transfixion','Scission'}},
    [145] = {en='Tachi: Hobaku',skillchain={'Induration'}},
    [146] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
    [147] = {en='Tachi: Kagero',skillchain={'Liquefaction'}},
    [148] = {en='Tachi: Jinpu',skillchain={'Scission','Detonation'}},
    [149] = {en='Tachi: Koki',skillchain={'Reverberation','Impaction'}},
    [150] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [151] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [152] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [153] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
    [154] = {en='Tachi: Rana',skillchain={'Gravitation','Induration'}},
    [155] = {en='Tachi: Ageha',skillchain={'Compression','Scission'}},
    [156] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
    [157] = {en='Tachi: Shoha',skillchain={'Fragmentation','Compression'},aeonic='Light',weapon='Dojikiri Yasutsuna'},
    [158] = {en='Tachi: Suikawari',skillchain={'Fusion'}},
--Club
    [160] = {en='Shining Strike',skillchain={'Impaction'}},
    [161] = {en='Seraph Strike',skillchain={'Impaction'}},
    [162] = {en='Brainshaker',skillchain={'Reverberation'}},
    [165] = {en='Skullbreaker',skillchain={'Induration','Reverberation'}},
    [166] = {en='True Strike',skillchain={'Impaction','Detonation'}},
    [167] = {en='Judgment',skillchain={'Impaction'}},
    [168] = {en='Hexa Strike',skillchain={'Fusion'}},
    [169] = {en='Black Halo',skillchain={'Fragmentation','Compression'}},
    [170] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
    [172] = {en='Flash Nova',skillchain={'Induration','Reverberation'}},
    [174] = {en='Realmrazer',skillchain={'Fusion','Impaction'},aeonic='Light',weapon='Tishtrya'},
--Staff
    [176] = {en='Heavy Swing',skillchain={'Impaction'}},
    [177] = {en='Rock Crusher',skillchain={'Impaction'}},
    [178] = {en='Earth Crusher',skillchain={'Detonation','Impaction'}},
    [179] = {en='Starburst',skillchain={'Compression','Reverberation'}},
    [180] = {en='Sunburst',skillchain={'Compression','Reverberation'}},
    [181] = {en='Shell Crusher',skillchain={'Detonation'}},
    [182] = {en='Full Swing',skillchain={'Liquefaction','Impaction'}},
    [184] = {en='Retribution',skillchain={'Gravitation','Reverberation'}},
    [185] = {en='Gate of Tartarus',skillchain={'Darkness','Distortion'}},
    [186] = {en='Vidohunir',skillchain={'Fragmentation','Distortion'}},
    [187] = {en='Garland of Bliss',skillchain={'Fusion','Reverberation'}},
    [188] = {en='Omniscience',skillchain={'Gravitation','Transfixion'}},
    [189] = {en='Cataclysm',skillchain={'Compression','Reverberation'}},
    [191] = {en='Shattersoul',skillchain={'Gravitation','Induration'},aeonic='Darkness',weapon='Khatvanga'},
--Archery
    [192] = {en='Flaming Arrow',skillchain={'Liquefaction','Transfixion'}},
    [193] = {en='Piercing Arrow',skillchain={'Reverberation','Transfixion'}},
    [194] = {en='Dulling Arrow',skillchain={'Liquefaction','Transfixion'}},
    [196] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
    [197] = {en='Blast Arrow',skillchain={'Induration','Transfixion'}},
    [198] = {en='Arching Arrow',skillchain={'Fusion'}},
    [199] = {en='Empyreal Arrow',skillchain={'Fusion','Transfixion'}},
    [200] = {en='Namas Arrow',skillchain={'Light','Distortion'}},
    [201] = {en='Refulgent Arrow',skillchain={'Reverberation','Transfixion'}},
    [202] = {en='Jishnu\'s Radiance',skillchain={'Light','Fusion'}},
    [203] = {en='Apex Arrow',skillchain={'Fragmentation','Transfixion'},aeonic='Light',weapon='Fail-Not'},
--Marksmanship
    [208] = {en='Hot Shot',skillchain={'Liquefaction','Transfixion'}},
    [209] = {en='Split Shot',skillchain={'Reverberation','Transfixion'}},
    [210] = {en='Sniper Shot',skillchain={'Liquefaction','Transfixion'}},
    [212] = {en='Slug Shot',skillchain={'Reverberation','Transfixion','Detonation'}},
    [213] = {en='Blast Shot',skillchain={'Induration','Transfixion'}},
    [214] = {en='Heavy Shot',skillchain={'Fusion'}},
    [215] = {en='Detonator',skillchain={'Fusion','Transfixion'}},
    [216] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
    [217] = {en='Trueflight',skillchain={'Fragmentation','Scission'}},
    [218] = {en='Leaden Salute',skillchain={'Gravitation','Transfixion'}},
    [219] = {en='Numbing Shot',skillchain={'Induration','Detonation','Impaction'}},
    [220] = {en='Wildfire',skillchain={'Darkness','Gravitation'}},
    [221] = {en='Last Stand',skillchain={'Fusion','Reverberation'},aeonic='Light',weapon='Fomalhaut'},
}

sets.phoenix[13] = {
--Carbuncle
    [513] = {en='Poison Nails',skillchain={'Transfixion'},avatar='Carbuncle',level=5},
    [521] = {en='Regal Scratch',skillchain={'Scission'},avatar='Carbuncle',level=1},
--Fenrir
    [528] = {en='Moonlit Charge',skillchain={'Compression'},avatar='Fenrir',level=5},
    [529] = {en='Crescent Fang',skillchain={'Transfixion'},avatar='Fenrir',level=10},
--Ifrit
    [544] = {en='Punch',skillchain={'Liquefaction'},avatar='Ifrit',level=1},
    [546] = {en='Burning Strike',skillchain={'Impaction'},avatar='Ifrit',level=23},
    [547] = {en='Double Punch',skillchain={'Compression'},avatar='Ifrit',level=30},
--Titan
    [560] = {en='Rock Throw',skillchain={'Scission'},avatar='Titan',level=1},
    [562] = {en='Rock Buster',skillchain={'Reverberation'},avatar='Titan',level=21},
    [563] = {en='Megalith Throw',skillchain={'Induration'},avatar='Titan',level=35},
    [570] = {en='Crag Throw',skillchain={'Gravitation','Scission'},avatar='Titan',level=99},
--Leviathan
    [576] = {en='Barracuda Dive',skillchain={'Reverberation'},avatar='Leviathan',level=1},
    [578] = {en='Tail Whip',skillchain={'Detonation'},avatar='Leviathan',level=26},
--Garuda
    [592] = {en='Claw',skillchain={'Detonation'},avatar='Garuda',level=1},
--Shiva
    [608] = {en='Axe Kick',skillchain={'Induration'},avatar='Shiva',level=1},
    [612] = {en='Double Slap',skillchain={'Scission'},avatar='Shiva',level=50},
--Ramuh
    [624] = {en='Shock Strike',skillchain={'Impaction'},avatar='Ramuh',level=1},
    [634] = {en='Volt Strike',skillchain={'Fragmentation','Scission'},avatar='Ramuh',level=99},
--Diabolos
    [656] = {en='Camisado',skillchain={'Compression'},avatar='Diabolos',level=1},
    [667] = {en='Blindside',skillchain={'Gravitation','Transfixion'},avatar='Diabolos',level=99},
}

sets.phoenix[14] = {
--Samurai
    [320] = {en='Konzen-ittai',skillchain={'Light','Darkness','Gravitation','Fragmentation','Distortion','Compression','Liquefaction','Induration','Reverberation','Scission'}},
--Dancer
    [209] = {en='Wild Flourish',skillchain={'Compression','Liquefaction','Induration','Reverberation','Scission'}},
}

sets.phoenix.immanence = {
    [1] = {en='Fire',skillchain={'Liquefaction'}},
    [2] = {en='Ice',skillchain={'Induration'}},
    [3] = {en='Wind',skillchain={'Detonation'}},
    [4] = {en='Earth',skillchain={'Scission'}},
    [5] = {en='Lightning',skillchain={'Impaction'}},
    [6] = {en='Water',skillchain={'Reverberation'}},
    [7] = {en='Light',skillchain={'Transfixion'}},
    [8] = {en='Dark',skillchain={'Compression'}},
}

sets.phoenix[4] = {
--Blue Mage
    [519] = {en='Screwdriver',skillchain={'Transfixion','Scission'}},
    [527] = {en='Smite of Rage',skillchain={'Detonation'}},
    [529] = {en='Bludgeon',skillchain={'Liquefaction'}},
    [539] = {en='Terror Touch',skillchain={'Compression','Reverberation'}},
    [540] = {en='Spinal Cleave',skillchain={'Scission','Detonation'}},
    [543] = {en='Mandibular Bite',skillchain={'Induration'}},
    [545] = {en='Sickle Slash',skillchain={'Compression'}},
    [551] = {en='Power Attack',skillchain={'Reverberation'}},
    [554] = {en='Death Scissors',skillchain={'Compression','Reverberation'}},
    [560] = {en='Frenetic Rip',skillchain={'Induration'}},
    [564] = {en='Body Slam',skillchain={'Impaction'}},
    [567] = {en='Helldive',skillchain={'Transfixion'}},
    [569] = {en='Jet Stream',skillchain={'Impaction'}},
    [577] = {en='Foot Kick',skillchain={'Detonation'}},
    [585] = {en='Ram Charge',skillchain={'Fragmentation'}},
    [587] = {en='Claw Cyclone',skillchain={'Scission'}},
    [589] = {en='Dimensional Death',skillchain={'Transfixion','Impaction'}},
    [594] = {en='Uppercut',skillchain={'Liquefaction','Impaction'}},
    [596] = {en='Pinecone Bomb',skillchain={'Liquefaction'}},
    [597] = {en='Sprout Smack',skillchain={'Reverberation'}},
    [599] = {en='Queasyshroom',skillchain={'Compression'}},
    [603] = {en='Wild Oats',skillchain={'Transfixion'}},
    [611] = {en='Disseverment',skillchain={'Distortion'}},
    [617] = {en='Vertical Cleave',skillchain={'Gravitation'}},
    [620] = {en='Battle Dance',skillchain={'Impaction'}},
    [622] = {en='Grand Slam',skillchain={'Induration'}},
    [623] = {en='Head Butt',skillchain={'Impaction'}},
    [628] = {en='Frypan',skillchain={'Impaction'}},
    [631] = {en='Hydro Shot',skillchain={'Reverberation'}},
    [638] = {en='Feather Storm',skillchain={'Transfixion'}},
    [640] = {en='Tail Slap',skillchain={'Reverberation'}},
    [641] = {en='Hysteric Barrage',skillchain={'Detonation'}},
    [643] = {en='Cannonball',skillchain={'Fusion'}},
    [650] = {en='Seedspray',skillchain={'Induration','Detonation'}},
    [652] = {en='Spiral Spin',skillchain={'Transfixion'}},
    [653] = {en='Asuran Claws',skillchain={'Liquefaction','Impaction'}},
    [654] = {en='Sub-Zero Smash',skillchain={'Fragmentation'}},
    [665] = {en='Final Sting',skillchain={'Fusion'}},
    [666] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [669] = {en='Whirl of Rage',skillchain={'Scission','Detonation'}},
    [670] = {en='Benthic Typhoon',skillchain={'Gravitation','Transfixion'}},
    [673] = {en='Quadratic Continuum',skillchain={'Distortion','Scission'}},
    [677] = {en='Empty Thrash',skillchain={'Compression','Scission'}},
    [682] = {en='Delta Thrust',skillchain={'Liquefaction','Detonation'}},
    [688] = {en='Heavy Strike',skillchain={'Fragmentation','Transfixion'}},
    [692] = {en='Sudden Lunge',skillchain={'Detonation'}},
    [693] = {en='Quadrastrike',skillchain={'Liquefaction','Scission','Impaction'}},
    [697] = {en='Amorphic Spikes',skillchain={'Gravitation'}},
    [699] = {en='Barbed Crescent',skillchain={'Distortion','Scission'}},
    [740] = {en='Tourbillion',skillchain={'Light','Fragmentation'}},
    [742] = {en='Bilgestorm',skillchain={'Darkness','Gravitation'}},
    [743] = {en='Bloodrake',skillchain={'Darkness','Distortion'}},
--Scholar
    [144] = {en='Fire',skillchain={'Liquefaction'}},
    [145] = {en='Fire II',skillchain={'Liquefaction'}},
    [146] = {en='Fire III',skillchain={'Liquefaction'}},
    [147] = {en='Fire IV',skillchain={'Liquefaction'}},
    [148] = {en='Fire V',skillchain={'Liquefaction'}},
    [149] = {en='Blizzard',skillchain={'Induration'}},
    [150] = {en='Blizzard II',skillchain={'Induration'}},
    [151] = {en='Blizzard III',skillchain={'Induration'}},
    [152] = {en='Blizzard IV',skillchain={'Induration'}},
    [153] = {en='Blizzard V',skillchain={'Induration'}},
    [154] = {en='Aero',skillchain={'Detonation'}},
    [155] = {en='Aero II',skillchain={'Detonation'}},
    [156] = {en='Aero III',skillchain={'Detonation'}},
    [157] = {en='Aero IV',skillchain={'Detonation'}},
    [158] = {en='Aero V',skillchain={'Detonation'}},
    [159] = {en='Stone',skillchain={'Scission'}},
    [160] = {en='Stone II',skillchain={'Scission'}},
    [161] = {en='Stone III',skillchain={'Scission'}},
    [162] = {en='Stone IV',skillchain={'Scission'}},
    [163] = {en='Stone V',skillchain={'Scission'}},
    [164] = {en='Thunder',skillchain={'Impaction'}},
    [165] = {en='Thunder II',skillchain={'Impaction'}},
    [166] = {en='Thunder III',skillchain={'Impaction'}},
    [167] = {en='Thunder IV',skillchain={'Impaction'}},
    [168] = {en='Thunder V',skillchain={'Impaction'}},
    [169] = {en='Water',skillchain={'Reverberation'}},
    [170] = {en='Water II',skillchain={'Reverberation'}},
    [171] = {en='Water III',skillchain={'Reverberation'}},
    [172] = {en='Water IV',skillchain={'Reverberation'}},
    [173] = {en='Water V',skillchain={'Reverberation'}},
    [278] = {en='Geohelix',skillchain={'Scission'},delay=5},
    [279] = {en='Hydrohelix',skillchain={'Reverberation'},delay=5},
    [280] = {en='Anemohelix',skillchain={'Detonation'},delay=5},
    [281] = {en='Pyrohelix',skillchain={'Liquefaction'},delay=5},
    [282] = {en='Cryohelix',skillchain={'Induration'},delay=5},
    [283] = {en='Ionohelix',skillchain={'Impaction'},delay=5},
    [284] = {en='Noctohelix',skillchain={'Compression'},delay=5},
    [285] = {en='Luminohelix',skillchain={'Transfixion'},delay=5},
    [503] = {en='Impact',skillchain={'Compression'}},
    [885] = {en='Geohelix II',skillchain={'Scission'},delay=5},
    [886] = {en='Hydrohelix II',skillchain={'Reverberation'},delay=5},
    [887] = {en='Anemohelix II',skillchain={'Detonation'},delay=5},
    [888] = {en='Pyrohelix II',skillchain={'Liquefaction'},delay=5},
    [889] = {en='Cryohelix II',skillchain={'Induration'},delay=5},
    [890] = {en='Ionohelix II',skillchain={'Impaction'},delay=5},
    [891] = {en='Noctohelix II',skillchain={'Compression'},delay=5},
    [892] = {en='Luminohelix II',skillchain={'Transfixion'},delay=5},
}

sets.phoenix.pup = {
    [1940] = {en='Chimera Ripper',skillchain={'Induration','Detonation'}},
    [1941] = {en='String Clipper',skillchain={'Scission','Impaction'}},
    [1942] = {en='Arcuballista',skillchain={'Liquefaction','Transfixion'}},
    [1943] = {en='Slapstick',skillchain={'Reverberation','Impaction'}},
    [2065] = {en='Cannibal Blade',skillchain={'Compression','Reverberation'}},
    [2066] = {en='Daze',skillchain={'Transfixion'}},
    [2067] = {en='Knockout',skillchain={'Scission','Detonation'}},
    [2299] = {en='Bone Crusher',skillchain={'Fragmentation'}},
    [2300] = {en='Armor Piercer',skillchain={'Gravitation'}},
    [2301] = {en='Magic Mortar',skillchain={'Fusion'}},
    [2743] = {en='String Shredder',skillchain={'Distortion','Scission'}},
    [2744] = {en='Armor Shatterer',skillchain={'Fusion','Impaction'}},
}

sets.phoenix.bst = {
    [3840] = {en='Foot Kick',skillchain={'Reverberation'}},
    [3842] = {en='Whirl Claws',skillchain={'Impaction'}},
    [3843] = {en='Head Butt',skillchain={'Detonation'}},
    [3845] = {en='Wild Oats',skillchain={'Transfixion'}},
    [3846] = {en='Leaf Dagger',skillchain={'Scission'}},
    [3849] = {en='Razor Fang',skillchain={'Impaction'}},
    [3850] = {en='Claw Cyclone',skillchain={'Scission'}},
    [3851] = {en='Tail Blow',skillchain={'Impaction'}},
    [3853] = {en='Blockhead',skillchain={'Reverberation'}},
    [3854] = {en='Brain Crush',skillchain={'Liquefaction'}},
    [3857] = {en='Lamb Chop',skillchain={'Impaction'}},
    [3859] = {en='Sheep Charge',skillchain={'Reverberation'}},
    [3863] = {en='Big Scissors',skillchain={'Scission'}},
    [3866] = {en='Needleshot',skillchain={'Transfixion'}},
    [3867] = {en='Random Needles',skillchain={'Darkness','Fragmentation'}},
    [3868] = {en='Frogkick',skillchain={'Compression'}},
    [3875] = {en='Power Attack',skillchain={'Reverberation'}},
    [3877] = {en='Rhino Attack',skillchain={'Detonation'}},
    [3885] = {en='Mandibular Bite',skillchain={'Detonation'}},
    [3891] = {en='Nimble Snap',skillchain={'Impaction'}},
    [3892] = {en='Cyclotail',skillchain={'Impaction'}},
    [3894] = {en='Double Claw',skillchain={'Liquefaction'}},
    [3895] = {en='Grapple',skillchain={'Reverberation'}},
    [3897] = {en='Spinning Top',skillchain={'Impaction'}},
    [3900] = {en='Suction',skillchain={'Compression'}},
    [3904] = {en='Sudden Lunge',skillchain={'Impaction'}},
    [3905] = {en='Spiral Spin',skillchain={'Scission'}},
    [3909] = {en='Scythe Tail',skillchain={'Liquefaction'}},
    [3910] = {en='Ripper Fang',skillchain={'Induration'}},
    [3911] = {en='Chomp Rush',skillchain={'Darkness','Gravitation'}},
    [3915] = {en='Back Heel',skillchain={'Reverberation'}},
    [3919] = {en='Tortoise Stomp',skillchain={'Liquefaction'}},
    [3922] = {en='Wing Slap',skillchain={'Gravitation','Liquefaction'}},
    [3923] = {en='Beak Lunge',skillchain={'Scission'}},
    [3925] = {en='Recoil Dive',skillchain={'Transfixion'}},
    [3927] = {en='Sensilla Blades',skillchain={'Scission'}},
    [3928] = {en='Tegmina Buffet',skillchain={'Distortion','Detonation'}},
    [3930] = {en='Swooping Frenzy',skillchain={'Fusion','Reverberation'}},
    [3933] = {en='Pentapeck',skillchain={'Light','Distortion'}},
    [3938] = {en='Somersault',skillchain={'Compression'}},
    [3955] = {en='Rhinowrecker',skillchain={'Fusion','Scission'}},
    [3959] = {en='Crossthrash',skillchain={'Distortion','Detonation'}},
    [3961] = {en='Hoof Volley',skillchain={'Fragmentation'}},
}

sets.phoenix[11] = {
--Hand-to-Hand
    [1] = {en='Combo',skillchain={'Impaction'}},
    [2] = {en='Shoulder Tackle',skillchain={'Reverberation','Impaction'}},
    [3] = {en='One Inch Punch',skillchain={'Compression'}},
    [4] = {en='Backhand Blow',skillchain={'Detonation'}},
    [5] = {en='Raging Fists',skillchain={'Impaction'}},
    [6] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
    [7] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [8] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [9] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [10] = {en='Final Heaven',skillchain={'Light','Fusion'}},
    [11] = {en='Ascetics Fury',skillchain={'Fusion','Transfixion'}},
    [12] = {en='Stringing Pummel',skillchain={'Gravitation','Liquefaction'}},
    [13] = {en='Tornado Kick',skillchain={'Induration','Impaction','Detonation'}},
    [14] = {en='Victory Smite',skillchain={'Light','Fragmentation'}},
    [15] = {en='Shijin Spiral',skillchain={'Fusion','Reverberation'}},
    [228] = {en='Final Paradise',skillchain={'Light'}},
    [1027] = {en='Combo',skillchain={'Impaction'}},
    [1029] = {en='One-ilm Punch',skillchain={'Compression'}},
    [1030] = {en='Backhand Blow',skillchain={'Detonation'}},
    [1031] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
    [1032] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [1033] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [1034] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [3234] = {en='Nullifying Dropkick',skillchain={'Induration','Detonation','Impaction'}},
    [3235] = {en='Auroral Uppercut',skillchain={'Light','Fragmentation'}},
    [3236] = {en='Knuckle Sandwich',skillchain={'Fusion','Compression','Impaction'}},
    [3413] = {en='Combo',skillchain={'Impaction'}},
    [3414] = {en='One-ilm Punch',skillchain={'Compression'}},
    [3415] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [3416] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [3417] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
--Dagger
    [16] = {en='Wasp Sting',skillchain={'Scission'}},
    [17] = {en='Viper Bite',skillchain={'Scission'}},
    [18] = {en='Shadowstitch',skillchain={'Reverberation'}},
    [19] = {en='Gust Slash',skillchain={'Detonation'}},
    [20] = {en='Cyclone',skillchain={'Detonation','Impaction'}},
    [23] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
    [24] = {en='Shark Bite',skillchain={'Fragmentation'}},
    [25] = {en='Evisceration',skillchain={'Gravitation','Transfixion'}},
    [26] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
    [27] = {en='Mandalic Stab',skillchain={'Fusion','Compression'}},
    [28] = {en='Mordant Rime',skillchain={'Fragmentation','Distortion'}},
    [29] = {en='Pyrrhic Kleos',skillchain={'Distortion','Scission'}},
    [30] = {en='Aeolian Edge',skillchain={'Scission','Detonation','Impaction'}},
    [31] = {en='Rudras Storm',skillchain={'Darkness','Distortion'}},
    [224] = {en='Exenterator',skillchain={'Fragmentation','Scission'}},
--Sword
    [32] = {en='Fast Blade',skillchain={'Scission'}},
    [33] = {en='Burning Blade',skillchain={'Liquefaction'}},
    [34] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [35] = {en='Flat Blade',skillchain={'Impaction'}},
    [36] = {en='Shining Blade',skillchain={'Scission'}},
    [37] = {en='Seraph Blade',skillchain={'Scission'}},
    [38] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [40] = {en='Vorpal Blade',skillchain={'Reverberation','Impaction'}},
    [41] = {en='Swift Blade',skillchain={'Gravitation'}},
    [42] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [43] = {en='Knights Of Round',skillchain={'Light','Fusion'}},
    [44] = {en='Death Blossom',skillchain={'Fragmentation','Distortion'}},
    [45] = {en='Atonement',skillchain={'Fusion','Reverberation'}},
    [46] = {en='Expiacion',skillchain={'Distortion','Scission'}},
    [225] = {en='Chant Du Cygne',skillchain={'Light','Distortion'}},
    [226] = {en='Requiescat',skillchain={'Gravitation','Scission'}},
    [227] = {en='Knights Of Rotund',skillchain={'Fusion'}},
    [238] = {en='Uriel Blade',skillchain={'Light','Fragmentation','Scission'}},
    [239] = {en='Glory Slash',skillchain={'Light','Fusion'}},
    [938] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [939] = {en='Swift Blade',skillchain={'Gravitation'}},
    [943] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [968] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [969] = {en='Flat Blade',skillchain={'Impaction'}},
    [970] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [973] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [975] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [1737] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [3192] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [3216] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [3217] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [3432] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [3708] = {en='Swift Blade',skillchain={'Gravitation'}},
    [3709] = {en='Chant Du Cygne',skillchain={'Light','Distortion'}},
    [3711] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [3713] = {en='Chant Du Cygne',skillchain={'Light','Distortion'}},
--Great Sword
    [48] = {en='Hard Slash',skillchain={'Scission'}},
    [49] = {en='Power Slash',skillchain={'Scission'}},
    [50] = {en='Frostbite',skillchain={'Induration'}},
    [51] = {en='Freezebite',skillchain={'Induration','Detonation'}},
    [52] = {en='Shockwave',skillchain={'Reverberation'}},
    [53] = {en='Crescent Moon',skillchain={'Scission'}},
    [54] = {en='Sickle Moon',skillchain={'Scission','Impaction'}},
    [55] = {en='Spinning Slash',skillchain={'Fragmentation'}},
    [56] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [57] = {en='Scourge',skillchain={'Light','Fusion'}},
    [58] = {en='Herculean Slash',skillchain={'Induration','Impaction','Detonation'}},
    [59] = {en='Torcleaver',skillchain={'Light','Distortion'}},
    [60] = {en='Resolution',skillchain={'Fragmentation','Scission'}},
    [61] = {en='Dimidiation',skillchain={'Light','Fragmentation'}},
    [979] = {en='Power Slash',skillchain={'Transfixion'}},
    [980] = {en='Freeze Bite',skillchain={'Induration','Detonation'}},
    [981] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [987] = {en='Shockwave',skillchain={'Induration','Detonation'}},
--Axe
    [64] = {en='Raging Axe',skillchain={'Detonation','Impaction'}},
    [65] = {en='Smash Axe',skillchain={'Induration','Reverberation'}},
    [66] = {en='Gale Axe',skillchain={'Detonation'}},
    [67] = {en='Avalanche Axe',skillchain={'Scission','Impaction'}},
    [68] = {en='Spinning Axe',skillchain={'Liquefaction','Scission','Impaction'}},
    [69] = {en='Rampage',skillchain={'Scission'}},
    [70] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [71] = {en='Mistral Axe',skillchain={'Fusion'}},
    [72] = {en='Decimation',skillchain={'Fusion','Reverberation'}},
    [73] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
    [74] = {en='Primal Rend',skillchain={'Gravitation','Reverberation'}},
    [75] = {en='Bora Axe',skillchain={'Scission','Detonation'}},
    [76] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
    [77] = {en='Ruinator',skillchain={'Distortion','Detonation'}},
    [940] = {en='Rampage',skillchain={'Scission'}},
    [941] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [3715] = {en='Rampage',skillchain={'Scission'}},
    [3716] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [3718] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
--Great Axe
    [80] = {en='Shield Break',skillchain={'Impaction'}},
    [81] = {en='Iron Tempest',skillchain={'Scission'}},
    [82] = {en='Sturmwind',skillchain={'Reverberation','Scission'}},
    [83] = {en='Armor Break',skillchain={'Impaction'}},
    [84] = {en='Keen Edge',skillchain={'Compression'}},
    [85] = {en='Weapon Break',skillchain={'Impaction'}},
    [86] = {en='Raging Rush',skillchain={'Induration','Reverberation'}},
    [87] = {en='Full Break',skillchain={'Distortion'}},
    [88] = {en='Steel Cyclone',skillchain={'Distortion','Detonation'}},
    [89] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
    [90] = {en='Kings Justice',skillchain={'Fragmentation','Scission'}},
    [91] = {en='Fell Cleave',skillchain={'Scission','Detonation','Impaction'}},
    [92] = {en='Ukkos Fury',skillchain={'Light','Fragmentation'}},
    [93] = {en='Upheaval',skillchain={'Fusion','Compression'}},
--Scythe
    [96] = {en='Slice',skillchain={'Scission'}},
    [97] = {en='Dark Harvest',skillchain={'Reverberation'}},
    [98] = {en='Shadow Of Death',skillchain={'Induration','Reverberation'}},
    [99] = {en='Nightmare Scythe',skillchain={'Compression','Scission'}},
    [100] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [101] = {en='Vorpal Scythe',skillchain={'Transfixion','Scission'}},
    [102] = {en='Guillotine',skillchain={'Induration'}},
    [103] = {en='Cross Reaper',skillchain={'Distortion'}},
    [104] = {en='Spiral Hell',skillchain={'Distortion','Scission'}},
    [105] = {en='Catastrophe',skillchain={'Darkness','Gravitation'}},
    [106] = {en='Insurgency',skillchain={'Fusion','Compression'}},
    [107] = {en='Infernal Scythe',skillchain={'Compression','Reverberation'}},
    [108] = {en='Quietus',skillchain={'Darkness','Distortion'}},
    [109] = {en='Entropy',skillchain={'Gravitation','Reverberation'}},
    [944] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [945] = {en='Guillotine',skillchain={'Induration'}},
    [3721] = {en='Guillotine',skillchain={'Induration'}},
--Polearm
    [112] = {en='Double Thrust',skillchain={'Transfixion'}},
    [113] = {en='Thunder Thrust',skillchain={'Transfixion','Impaction'}},
    [114] = {en='Raiden Thrust',skillchain={'Transfixion','Impaction'}},
    [115] = {en='Leg Sweep',skillchain={'Impaction'}},
    [116] = {en='Penta Thrust',skillchain={'Compression'}},
    [117] = {en='Vorpal Thrust',skillchain={'Reverberation','Transfixion'}},
    [118] = {en='Skewer',skillchain={'Transfixion','Impaction'}},
    [119] = {en='Wheeling Thrust',skillchain={'Fusion'}},
    [120] = {en='Impulse Drive',skillchain={'Gravitation','Induration'}},
    [121] = {en='Geirskogul',skillchain={'Light','Distortion'}},
    [122] = {en='Drakesbane',skillchain={'Fusion','Transfixion'}},
    [123] = {en='Sonic Thrust',skillchain={'Transfixion','Scission'}},
    [124] = {en='Camlanns Torment',skillchain={'Light','Fragmentation'}},
    [125] = {en='Stardiver',skillchain={'Gravitation','Transfixion'}},
--Katana
    [128] = {en='Blade: Rin',skillchain={'Transfixion'}},
    [129] = {en='Blade: Retsu',skillchain={'Scission'}},
    [130] = {en='Blade: Teki',skillchain={'Reverberation'}},
    [131] = {en='Blade: To',skillchain={'Induration','Detonation'}},
    [132] = {en='Blade: Chi',skillchain={'Transfixion','Impaction'}},
    [133] = {en='Blade: Ei',skillchain={'Compression'}},
    [134] = {en='Blade: Jin',skillchain={'Detonation','Impaction'}},
    [135] = {en='Blade: Ten',skillchain={'Gravitation'}},
    [136] = {en='Blade: Ku',skillchain={'Gravitation','Transfixion'}},
    [137] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    [138] = {en='Blade: Kamu',skillchain={'Fragmentation','Compression'}},
    [139] = {en='Blade: Yu',skillchain={'Reverberation','Scission'}},
    [140] = {en='Blade: Hi',skillchain={'Darkness','Gravitation'}},
    [141] = {en='Blade: Shun',skillchain={'Fusion','Impaction'}},
--Great Katana
    [144] = {en='Tachi: Enpi',skillchain={'Transfixion','Scission'}},
    [145] = {en='Tachi: Hobaku',skillchain={'Induration'}},
    [146] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
    [147] = {en='Tachi: Kagero',skillchain={'Liquefaction'}},
    [148] = {en='Tachi: Jinpu',skillchain={'Scission','Detonation'}},
    [149] = {en='Tachi: Koki',skillchain={'Reverberation','Impaction'}},
    [150] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [151] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [152] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [153] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
    [154] = {en='Tachi: Rana',skillchain={'Gravitation','Induration'}},
    [155] = {en='Tachi: Ageha',skillchain={'Compression','Scission'}},
    [156] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
    [157] = {en='Tachi: Shoha',skillchain={'Fragmentation','Compression'}},
    [158] = {en='Tachi: Suikawari',skillchain={'Fusion'}},
    [946] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [947] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [948] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [1390] = {en='Amatsu: Torimai',skillchain={'Transfixion','Scission'}},
    [1391] = {en='Amatsu: Kazakiri',skillchain={'Scission','Detonation'}},
    [1392] = {en='Amatsu: Yukiarashi',skillchain={'Induration','Detonation'}},
    [1393] = {en='Amatsu: Tsukioboro',skillchain={'Distortion','Reverberation'}},
    [1394] = {en='Amatsu: Hanaikusa',skillchain={'Fusion','Compression'}},
    [1395] = {en='Amatsu: Tsukikage',skillchain={'Fragmentation','Detonation'}},
    [3256] = {en='Hane Fubuki',skillchain={'Transfixion'}},
    [3257] = {en='Shibaraku',skillchain={'Darkness','Gravitation'}},
    [3259] = {en='Happobarai',skillchain={'Reverberation','Impaction'}},
    [3437] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [3542] = {en='Oisoya',skillchain={'Light','Distortion'}},
    [3722] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [3723] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [3725] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [3726] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
--Club
    [160] = {en='Shining Strike',skillchain={'Impaction'}},
    [161] = {en='Seraph Strike',skillchain={'Impaction'}},
    [162] = {en='Brainshaker',skillchain={'Reverberation'}},
    [165] = {en='Skullbreaker',skillchain={'Induration','Reverberation'}},
    [166] = {en='True Strike',skillchain={'Impaction','Detonation'}},
    [167] = {en='Judgment',skillchain={'Impaction'}},
    [168] = {en='Hexa Strike',skillchain={'Fusion'}},
    [169] = {en='Black Halo',skillchain={'Fragmentation','Compression'}},
    [170] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
    [172] = {en='Flash Nova',skillchain={'Induration','Reverberation'}},
    [174] = {en='Realmrazer',skillchain={'Fusion','Impaction'}},
    [3314] = {en='True Strike',skillchain={'Impaction','Detonation'}},
    [3315] = {en='Hexa Strike',skillchain={'Fusion'}},
--Staff
    [176] = {en='Heavy Swing',skillchain={'Impaction'}},
    [177] = {en='Rock Crusher',skillchain={'Impaction'}},
    [178] = {en='Earth Crusher',skillchain={'Detonation','Impaction'}},
    [179] = {en='Starburst',skillchain={'Compression','Reverberation'}},
    [180] = {en='Sunburst',skillchain={'Compression','Reverberation'}},
    [181] = {en='Shell Crusher',skillchain={'Detonation'}},
    [182] = {en='Full Swing',skillchain={'Liquefaction','Impaction'}},
    [184] = {en='Retribution',skillchain={'Gravitation','Reverberation'}},
    [185] = {en='Gate Of Tartarus',skillchain={'Darkness','Distortion'}},
    [186] = {en='Vidohunir',skillchain={'Fragmentation','Distortion'}},
    [187] = {en='Garland Of Bliss',skillchain={'Fusion','Reverberation'}},
    [188] = {en='Omniscience',skillchain={'Gravitation','Transfixion'}},
    [189] = {en='Cataclysm',skillchain={'Compression','Reverberation'}},
    [191] = {en='Shattersoul',skillchain={'Gravitation','Induration'}},
    [3470] = {en='Great Wheel',skillchain={'Fragmentation','Scission'}},
    [3471] = {en='Light Blade',skillchain={'Light','Fusion'}},
    [3472] = {en='Vortex',skillchain={'Distortion','Reverberation'}},
    [3473] = {en='Stellar Burst',skillchain={'Darkness','Gravitation'}},
--Archery
    [192] = {en='Flaming Arrow',skillchain={'Liquefaction','Transfixion'}},
    [193] = {en='Piercing Arrow',skillchain={'Reverberation','Transfixion'}},
    [194] = {en='Dulling Arrow',skillchain={'Liquefaction','Transfixion'}},
    [196] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
    [197] = {en='Blast Arrow',skillchain={'Induration','Transfixion'}},
    [198] = {en='Arching Arrow',skillchain={'Fusion'}},
    [199] = {en='Empyreal Arrow',skillchain={'Fusion','Transfixion'}},
    [200] = {en='Namas Arrow',skillchain={'Light','Distortion'}},
    [201] = {en='Refulgent Arrow',skillchain={'Reverberation','Transfixion'}},
    [202] = {en='Jishnus Radiance',skillchain={'Light','Fusion'}},
    [203] = {en='Apex Arrow',skillchain={'Fragmentation','Transfixion'}},
    [3487] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
    [3488] = {en='Arching Arrow',skillchain={'Fusion'}},
    [3489] = {en='Stellar Arrow',skillchain={'Darkness','Gravitation'}},
    [3490] = {en='Lux Arrow',skillchain={'Fragmentation','Distortion'}},
--Marksmanship
    [208] = {en='Hot Shot',skillchain={'Liquefaction','Transfixion'}},
    [209] = {en='Split Shot',skillchain={'Reverberation','Transfixion'}},
    [210] = {en='Sniper Shot',skillchain={'Liquefaction','Transfixion'}},
    [212] = {en='Slug Shot',skillchain={'Reverberation','Transfixion','Detonation'}},
    [213] = {en='Blast Shot',skillchain={'Induration','Transfixion'}},
    [214] = {en='Heavy Shot',skillchain={'Fusion'}},
    [215] = {en='Detonator',skillchain={'Fusion','Transfixion'}},
    [216] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
    [217] = {en='Trueflight',skillchain={'Fragmentation','Scission'}},
    [218] = {en='Leaden Salute',skillchain={'Gravitation','Transfixion'}},
    [219] = {en='Numbing Shot',skillchain={'Induration','Detonation','Impaction'}},
    [220] = {en='Wildfire',skillchain={'Darkness','Gravitation'}},
    [221] = {en='Last Stand',skillchain={'Fusion','Reverberation'}},
    [2891] = {en='Grapeshot',skillchain={'Liquefaction','Compression'}},
    [2892] = {en='Pirate Pummel',skillchain={'Gravitation'}},
    [2893] = {en='Powder Keg',skillchain={'Reverberation','Transfixion'}},
    [2894] = {en='Walk The Plank',skillchain={'Fusion'}},
    [3198] = {en='Grapeshot',skillchain={'Liquefaction','Compression'}},
    [3199] = {en='Pirate Pummel',skillchain={'Gravitation'}},
    [3200] = {en='Powder Keg',skillchain={'Reverberation','Transfixion'}},
    [3201] = {en='Walk The Plank',skillchain={'Fusion'}},
    [3491] = {en='Grapeshot',skillchain={'Liquefaction','Compression'}},
    [3492] = {en='Pirate Pummel',skillchain={'Gravitation'}},
    [3493] = {en='Powder Keg',skillchain={'Reverberation','Transfixion'}},
    [3494] = {en='Walk The Plank',skillchain={'Fusion'}},
--Other
    [62] = {en='Fimbulvetr',skillchain={'Distortion','Impaction','Detonation'}},
    [78] = {en='Blitz',skillchain={'Fragmentation','Impaction','Liquefaction'}},
    [94] = {en='Disaster',skillchain={'Gravitation','Scission','Transfixion'}},
    [110] = {en='Origin',skillchain={'Fusion','Induration','Reverberation'}},
    [126] = {en='Diarmuid',skillchain={'Distortion','Scission','Transfixion'}},
    [142] = {en='Zesho Meppo',skillchain={'Fusion','Induration','Reverberation'}},
    [159] = {en='Tachi: Mumei',skillchain={'Fusion','Induration','Reverberation'}},
    [204] = {en='Sarv',skillchain={'Gravitation','Scission','Transfixion'}},
    [222] = {en='Terminus',skillchain={'Fusion','Induration','Reverberation'}},
    [229] = {en='Fast Blade II',skillchain={'Fusion'}},
    [230] = {en='Dragon Blow',skillchain={'Distortion'}},
    [231] = {en='Maru Kala',skillchain={'Distortion','Detonation','Compression'}},
    [232] = {en='Ruthless Stroke',skillchain={'Fragmentation','Impaction','Liquefaction'}},
    [233] = {en='Imperator',skillchain={'Distortion','Detonation','Compression'}},
    [234] = {en='Dagda',skillchain={'Gravitation','Scission','Transfixion'}},
    [235] = {en='Oshala',skillchain={'Fusion','Induration','Reverberation'}},
    [831] = {en='Moonlit Charge',skillchain={'Compression'}},
    [832] = {en='Crescent Fang',skillchain={'Transfixion'}},
    [836] = {en='Eclipse Bite',skillchain={'Gravitation','Scission'}},
    [840] = {en='Punch',skillchain={'Liquefaction'}},
    [842] = {en='Burning Strike',skillchain={'Impaction'}},
    [843] = {en='Double Punch',skillchain={'Compression'}},
    [846] = {en='Flaming Crush',skillchain={'Fusion','Reverberation'}},
    [849] = {en='Rock Throw',skillchain={'Scission'}},
    [851] = {en='Rock Buster',skillchain={'Reverberation'}},
    [852] = {en='Megalith Throw',skillchain={'Induration'}},
    [855] = {en='Mountain Buster',skillchain={'Gravitation','Induration'}},
    [858] = {en='Barracuda Dive',skillchain={'Reverberation'}},
    [860] = {en='Tail Whip',skillchain={'Detonation'}},
    [864] = {en='Spinning Dive',skillchain={'Distortion','Detonation'}},
    [867] = {en='Claw',skillchain={'Detonation'}},
    [873] = {en='Predator Claws',skillchain={'Fragmentation','Scission'}},
    [876] = {en='Axe Kick',skillchain={'Induration'}},
    [880] = {en='Double Slap',skillchain={'Scission'}},
    [882] = {en='Rush',skillchain={'Distortion','Scission'}},
    [885] = {en='Shock Strike',skillchain={'Impaction'}},
    [891] = {en='Chaotic Strike',skillchain={'Fragmentation','Transfixion'}},
    [907] = {en='Poison Nails',skillchain={'Transfixion'}},
    [1028] = {en='Tackle',skillchain={'Reverberation','Impaction'}},
    [2092] = {en='Scouring Bubbles',skillchain={'Darkness','Distortion'}},
    [2448] = {en='Regal Scratch',skillchain={'Scission'}},
    [3189] = {en='King Cobra Clamp',skillchain={'Fragmentation','Distortion'}},
    [3203] = {en='Scouring Bubbles',skillchain={'Darkness','Distortion'}},
    [3237] = {en='Victory Beacon',skillchain={'Light','Distortion'}},
    [3243] = {en='Imperial Authority',skillchain={'Fragmentation','Distortion'}},
    [3261] = {en='Bomb Toss',skillchain={'Liquefaction','Detonation'}},
    [3262] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [3438] = {en='Dragon Breath',skillchain={'Light','Fusion'}},
    [3439] = {en='Hurricane Wing',skillchain={'Scission','Detonation'}},
    [3466] = {en='Paralyzing Microtube',skillchain={'Induration','Reverberation'}},
    [3467] = {en='Silencing Microtube',skillchain={'Liquefaction','Detonation'}},
    [3468] = {en='Binding Microtube',skillchain={'Gravitation','Induration'}},
    [3469] = {en='Twirling Dervish',skillchain={'Light','Fusion'}},
    [3496] = {en='Hollow Smite',skillchain={'Light','Fragmentation'}},
    [3653] = {en='Tartaric Sigil',skillchain={'Compression','Scission'}},
    [3654] = {en='Null Field',skillchain={'Fusion','Transfixion'}},
    [3655] = {en='Alabaster Burst',skillchain={'Distortion','Detonation'}},
    [3656] = {en='Noble Frenzy',skillchain={'Gravitation','Scission'}},
    [3657] = {en='Fulminous Fury',skillchain={'Fragmentation','Scission'}},
    [3658] = {en='No Quarter',skillchain={'Light','Distortion'}},
    [3740] = {en='Final Exam',skillchain={'Light','Fusion'}},
    [3741] = {en='Doctors Orders',skillchain={'Darkness','Gravitation'}},
    [3742] = {en='Empirical Research',skillchain={'Fragmentation','Transfixion'}},
    [3743] = {en='Lesson In Pain',skillchain={'Distortion','Scission'}},
}
return sets
